sudo: required
language: node_js
node_js:
 - "10.15.3"
services:
  - docker

before_install:
  - docker build -t akshaybabar/docker-react -f docketfile.dev .
  
script:
  - docker run akshaybabar/docker-react npm run test -- --coverage